#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  7 02:14:49 2018

@author: naveen
"""
import numpy as np
from scipy.io import loadmat
import math
from scipy.io import savemat


x = loadmat('/home/mtech07/Downloads/action recognition/data_needed/Testdata/a1_s2_t2_skeleton.mat')

a=x['d_skel']

n=a.shape[2]
n1 = a.shape[0]
result = []
for i in range(n-1):
    distance = []
    for j in range(n1):
        for k in range(n1):
            subSqr = np.subtract(a[:,:,i][j], a[:,:,i+1][k])**2
            distance.append(math.sqrt(sum(subSqr)))
    result.append(distance)  
    
output = np.asanyarray(result)

print(output)
savemat('frame.mat', {'vect': output})